#!/bin/sh

echo "installing xbps community module"
ansible-galaxy collection install community.general

echo "starting ansible tasks"
ansible-playbook bootstrap.yml -K

echo "Process completed. Reboot your system."
