- name: download dotfiles
  register: dotfiles
  git:
    repo: https://github.com/onur-ozkan/dotfiles
    dest: /tmp/dotfiles

- name: dotfiles installation
  become: no
  register: dotfilesinstallation
  shell: cd /tmp/dotfiles && ./install
  when: dotfiles is succeeded

- name: removing dotfiles source
  shell: rm -rf /tmp/dotfiles
  when: dotfilesinstallation is succeeded