---
- name: x packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - libX11-devel
    - libXft-devel
    - libXi-devel
    - libXinerama-devel
    - libXrandr-devel
    - xclip
    - xdg-utils
    - xorg-minimal
    - xrandr
    - xset

- name: audio packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - pipewire

- name: bluetooth packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - bluez
    - libspa-bluetooth

- name: environment(mostly wm and compositor)/development dependencies
  community.general.xbps:
    name: "{{item}}"
  loop:
    - dbus-devel
    - harfbuzz-devel
    - libconfig-devel
    - libdrm-devel
    - libev
    - libev-devel
    - lzop
    - mesa
    - mesa-dri
    - meson
    - pcre-devel
    - pixman-devel
    - readline-devel
    - uthash
    - xcb-util-image-devel
    - xcb-util-renderutil-devel

- name: laptop specific packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - brightnessctl
    - tlp
    - tlp-rdw

- name: personal packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - cmake
    - curl
    - flameshot
    - gcc
    - git
    - make
    - neovim
    - NetworkManager
    - opendoas
    - podman
    - ripgrep
    - setxkbmap
    - tmux
    - valgrind
    - zip
    - zsh
