---
- name: x packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - libX11-devel
    - libXft-devel
    - libXi-devel
    - libXinerama-devel
    - libXrandr-devel
    - xclip
    - xdg-utils
    - xorg-fonts
    - xorg-minimal
    - xrandr
    - xrdb
    - xset

- name: audio packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - alsa-pipewire
    - pipewire
    - wireplumber

- name: bluetooth packages
  when: bluetooth|default(false)|bool
  community.general.xbps:
    name: "{{item}}"
  loop:
    - bluez
    - libspa-bluetooth

- name: environment(mostly wm and compositor)/development dependencies
  community.general.xbps:
    name: "{{item}}"
  loop:
    - acpi
    - dbus-devel
    - harfbuzz-devel
    - imlib2-devel
    - libconfig-devel
    - libdrm-devel
    - libev
    - libev-devel
    - lzop
    - mesa
    - mesa-dri
    - meson
    - openssl-devel
    - pcre-devel
    - pixman-devel
    - pkg-config
    - readline-devel
    - uthash
    - xcb-util-image-devel
    - xcb-util-renderutil-devel

- name: laptop specific packages
  when: laptop|default(false)|bool
  community.general.xbps:
    name: "{{item}}"
  loop:
    - brightnessctl
    - powertop
    - tlp
    - tlp-rdw
    - xinput # not really needed on desktop, mostly used for disabling touchpad or touchscreen

- name: personal packages
  community.general.xbps:
    name: "{{item}}"
  loop:
    - bc
    - chrony
    - cmake
    - curl
    - fd
    - flameshot
    - gcc
    - git
    - htop
    - make
    - neovim
    - NetworkManager
    - opendoas
    - podman
    - qemu
    - ripgrep
    - setxkbmap
    - socklog
    - socklog-void
    - tmux
    - unzip
    - valgrind
    - void-repo-nonfree
    - wget
    - xtools
    - zip
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
