- name: download source packages
  register: sources
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - {
        repo: https://github.com/ozkanonur/dwm-enhanced,
        dest: /tmp/dwm-enhanced,
      }
    - { repo: https://github.com/ozkanonur/st-enhanced, dest: /tmp/st-enhanced }
    - {
        repo: https://github.com/ozkanonur/dmenu-enhanced,
        dest: /tmp/dmenu-enhanced,
      }
    - {
        repo: https://github.com/ozkanonur/dwmblocks-enhanced,
        dest: /tmp/dwmblocks-enhanced,
      }
    - {
        repo: https://github.com/ozkanonur/slock-enhanced,
        dest: /tmp/slock-enhanced,
      }
    - { repo: https://github.com/ozkanonur/sbs, dest: /tmp/sbs }
    - { repo: https://github.com/ibhagwan/picom, dest: /tmp/picom }

- name: building & installing dwm-enhanced
  register: dwmenhancedinstallation
  shell: cd /tmp/dwm-enhanced && make clean install
  when: sources is succeeded

- name: removing dwm-enhanced source
  shell: rm -rf /tmp/dwm-enhanced
  when: dwmenhancedinstallation is succeeded

- name: building & installing st-enhanced
  register: stenhancedinstallation
  shell: cd /tmp/st-enhanced && make clean install
  when: sources is succeeded

- name: removing st-enhanced source
  shell: rm -rf /tmp/st-enhanced
  when: stenhancedinstallation is succeeded

- name: building & installing dmenu-enhanced
  register: dmenuenhancedinstallation
  shell: cd /tmp/dmenu-enhanced && make clean install
  when: sources is succeeded

- name: removing dmenu-enhanced source
  shell: rm -rf /tmp/dmenu-enhanced
  when: dmenuenhancedinstallation is succeeded

- name: building & installing dwmblocks-enhanced
  register: dwmblocksenhancedinstallation
  shell: cd /tmp/dwmblocks-enhanced && make clean install
  when: sources is succeeded

- name: removing dwmblocks-enhanced source
  shell: rm -rf /tmp/dwmblocks-enhanced
  when: dwmblocksenhancedinstallation is succeeded

- name: building & installing slock-enhanced
  register: slockenhancedinstallation
  shell: cd /tmp/slock-enhanced && make clean install
  when: sources is succeeded

- name: removing slock-enhanced source
  shell: rm -rf /tmp/slock-enhanced
  when: slockenhancedinstallation is succeeded

- name: building & installing sbs
  register: sbsinstallation
  shell: cd /tmp/sbs && make clean install
  when: sources is succeeded

- name: removing sbs source
  shell: rm -rf /tmp/sbs
  when: sbsinstallation is succeeded

- name: building & installing picom
  register: picominstallation
  shell: cd /tmp/picom && git submodule update --init --recursive && meson --buildtype=release . build && ninja -C build && sudo ninja -C build install
  when: sources is succeeded

- name: removing picom source
  shell: rm -rf /tmp/picom
  when: picominstallation is succeeded
